# permissions for end users to view baremetalhosts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: baremetalhost-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: baremetal-host
    app.kubernetes.io/part-of: baremetal-host
    app.kubernetes.io/managed-by: kustomize
  name: baremetalhost-viewer-role
rules:
- apiGroups:
  - iaas.yusur.io.iaas.yusur.io
  resources:
  - baremetalhosts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - iaas.yusur.io.iaas.yusur.io
  resources:
  - baremetalhosts/status
  verbs:
  - get
